import os
from dotenv import load_dotenv

load_dotenv()

# нвстройки основного OpenRouter API
OPENROUTER_API_RATE_LIMIT_SEC = 3.0
OPENROUTER_API_BASE_URL = os.getenv("OPENROUTER_API_BASE_URL")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_MODEL = os.getenv("OPENROUTER_MODEL")

# запасные API ключи для OpenRouter
OPENROUTER_API_KEY_FALLBACK_1 = os.getenv("OPENROUTER_API_KEY_FALLBACK_1")
OPENROUTER_API_KEY_FALLBACK_2 = os.getenv("OPENROUTER_API_KEY_FALLBACK_2")
OPENROUTER_API_KEY_FALLBACK_3 = os.getenv("OPENROUTER_API_KEY_FALLBACK_3")
OPENROUTER_API_KEY_FALLBACK_4 = os.getenv("OPENROUTER_API_KEY_FALLBACK_4")
OPENROUTER_API_KEY_FALLBACK_5 = os.getenv("OPENROUTER_API_KEY_FALLBACK_5")

# настройки API Ollama (локальная модель)
OLLAMA_API_BASE_URL = os.getenv("OLLAMA_API_BASE_URL")
OLLAMA_API_KEY = os.getenv("OLLAMA_API_KEY")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL")

# Список конфигураций API: [(key, url, model), ...]
# OPENROUTER_APIS = [(OPENROUTER_API_KEY, OPENROUTER_API_BASE_URL, OPENROUTER_MODEL)]
OPENROUTER_APIS = []
# if OPENROUTER_API_KEY_FALLBACK_1:
#     OPENROUTER_APIS.append((OPENROUTER_API_KEY_FALLBACK_1, OPENROUTER_API_BASE_URL, OPENROUTER_MODEL))
# if OPENROUTER_API_KEY_FALLBACK_2:
#     OPENROUTER_APIS.append((OPENROUTER_API_KEY_FALLBACK_2, OPENROUTER_API_BASE_URL, OPENROUTER_MODEL))
# if OPENROUTER_API_KEY_FALLBACK_3:
#     OPENROUTER_APIS.append((OPENROUTER_API_KEY_FALLBACK_3, OPENROUTER_API_BASE_URL, OPENROUTER_MODEL))
# if OPENROUTER_API_KEY_FALLBACK_4:
#     OPENROUTER_APIS.append((OPENROUTER_API_KEY_FALLBACK_4, OPENROUTER_API_BASE_URL, OPENROUTER_MODEL))
# if OPENROUTER_API_KEY_FALLBACK_5:
#     OPENROUTER_APIS.append((OPENROUTER_API_KEY_FALLBACK_5, OPENROUTER_API_BASE_URL, OPENROUTER_MODEL))
if OLLAMA_API_KEY:
    OPENROUTER_APIS.append((OLLAMA_API_KEY, OLLAMA_API_BASE_URL, OLLAMA_MODEL))